platform :ios, '12.0'
use_frameworks!

target 'ThingySDK_Example' do
  pod 'IOSThingyLibrary', :path => '../'
  pod 'Charts', '~> 4'
  pod 'SDCAlertView', '~> 10.0'
  pod 'SWRevealViewController', '~> 2'
  pod 'KeychainSwift', '~> 20.0'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
