platform :ios, '8.0'
use_frameworks!

target 'ThingySDK_Example' do
  pod 'IOSThingyLibrary', :path => '../'
  pod 'Charts', '~> 3'
  pod 'SDCAlertView', '~> 7'
  pod 'SWRevealViewController', '~> 2'
  pod 'Keychain', '~> 0.3'

  target 'ThingySDK_Tests' do
    inherit! :search_paths
  pod 'Quick'
  pod 'Nimble', '~>7'
  end
end
