platform :ios, '9.0'
use_frameworks!

target 'ThingySDK_Example' do
  pod 'IOSThingyLibrary', :path => '../'
  pod 'Charts', '~> 3'
  pod 'SDCAlertView', '~> 10.0'
  pod 'SWRevealViewController', '~> 2'
  pod 'Keychain', '~> 0.3'
end
